# -*- coding: utf-8 -*-
"""IBM model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5OqDlWasTxhhtgnVZ8doqAtNwnnUr3a
"""

!pip install -U ibm-watson-machine-learning

from ibm_watson_machine_learning import APIClient
credentials ={
    "url":"https://jp-tok.ml.cloud.ibm.com",
    "apikey":"BHyalu2c7JN6n9cnvAVULvSKRYFVLMQ_m51toZ9Yk0nS"
}
client = APIClient(credentials)

def guid_from_space_name(client,deploy):
  space = client.spaces.get_details()
  return (next(item for item in space['resources'] if item['entity']['name']==deploy)['metadata']['id'])

space_uid = guid_from_space_name(client,'digitrecognition')
print("Space UID = " + space_uid)

client.set.default_space(space_uid)

client.repository.download("97d463b1-45ee-47f7-b8af-aed338794ce1", 'DigitRecog_IBM_model.tar.gz')